# Generated by Django 5.1.3 on 2024-11-10 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeuser',
            options={'verbose_name': 'CustomeUser', 'verbose_name_plural': 'CustomeUsers'},
        ),
        migrations.RemoveField(
            model_name='customeuser',
            name='username',
        ),
    ]
